// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/clearspace/ClearspaceHomeVariant.tsx": () => import("../components/mockups/clearspace/ClearspaceHomeVariant.tsx"),
  "./components/mockups/templates/SwissGridCRMDashboard-mtrk6j/App.tsx": () => import("../components/mockups/templates/SwissGridCRMDashboard-mtrk6j/App.tsx")
};
